language: python
python:
    - 2.7
    - 3.6
    - 3.7
    - 3.8
    - 3.9
    - "3.10-dev"

matrix:
    allow_failures:
        - python: 3.7
        - python: 3.8
        - python: 3.9
        - python: "3.10-dev"

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y
        libportmidi-dev
        libsdl-image1.2-dev
        libsdl-mixer1.2-dev
        libsdl-ttf2.0-dev
        libsdl1.2-dev
        libsoundtouch-dev
        libvorbis-dev

install:
    - pip install cython
    - pip install coverage coveralls

script:
    - python setup.py check
    #- python setup.py test
    - coverage run --source='fretwork' setup.py test

after_success:
    - coveralls
