name: Tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: tests on ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.7']
        experimental: [false]

        include:
          - python-version: '3.8'
            experimental: true
          - python-version: '3.9'
            experimental: true
          - python-version: '3.10'
            experimental: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install os dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -yq \
            libportmidi-dev \
            libsdl-image1.2-dev \
            libsdl-mixer1.2-dev \
            libsdl-ttf2.0-dev \
            libsdl1.2-dev \
            libsoundtouch-dev \
            libvorbis-dev

      - name: Install python dependencies
        run: |
          pip install coverage pytest pytest-cov
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python setup.py check
          pytest --cov=fretwork
        env:
          SDL_AUDIODRIVER: dummy

      - name: Upload coverage
        if: ${{ matrix.python-version == '3.7' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install coveralls
          coveralls --service=github
