name: Tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: "tests on ${{ matrix.python-version }} (optional: ${{ matrix.experimental }})"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        experimental: [false]

        include:
          - python-version: '3.11'
            experimental: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install python dependencies (optional: ${{ matrix.experimental }})"
        continue-on-error: ${{ matrix.experimental }}
        run: |
          pip install coverage pytest pytest-cov
          pip install -r requirements.txt

      - name: "Run tests (optional: ${{ matrix.experimental }})"
        continue-on-error: ${{ matrix.experimental }}
        run: |
          python setup.py check
          pytest --cov=fretwork
        env:
          SDL_AUDIODRIVER: dummy

      - name: Upload coverage
        if: ${{ matrix.python-version == '3.7' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install coveralls
          coveralls --service=github
